Experiment Results:

Test on correct code:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    print(sieve(10))
          ^^^^^
NameError: name 'sieve' is not defined
```

Test on mutant:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    print(sieve(10))
          ^^^^^
NameError: name 'sieve' is not defined
```

Conclusion:
